import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import TanStackProvider from '@/components/TanStackProvider';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'NoteHub',
    description: 'Generated by create note',
    icons: { icon: '/icon.png' },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <TanStackProvider>
            <html lang="en">
                <body className={`${geistSans.variable} ${geistMono.variable}`}>
                    <Header />
                    <main>{children}</main>
                    <Footer />
                </body>
            </html>
        </TanStackProvider>
    );
}
